### ISSUE TITLE
Example compilation error

### ISSUE THREAD

**Issue by ol-ev** [OPEnSLab-OSU/SSLClient#12]
Hello,

I am going to use the library in my project on Arduino Due. First I tried to build EthernetMQTT example, but it failed. Among a dozen of warnings there is an error:
In constructor 'SSLClientParameters::SSLClientParameters(const char*, size_t, const char*, size_t, bool)':
\Documents\Arduino\libraries\SSLClient\src\SSLClientParameters.cpp:84:121: error: cannot convert 'br_skey_decoder_context' to 'uint32_t {aka long unsigned int}' in initialization, m_key_struct{ make_key_from_der( is_der ? std::vector<char>(key, key + key_len) : make_vector_pem(key, key_len) ) } {}
Could you help me with finding the source of the problem?

Looking forward to your reply,
Oleg I.

**Comment by prototypicalpro** [comment]
Yup, it looks like the older compiler used by the Arduino SAM core didn't like some of the syntax I was using. The issue should be fixed in SSLClient `1.6.5`.
