### ISSUE TITLE
Disconnection while receiving a large message

### ISSUE THREAD

**Issue by Mark-81** [OPEnSLab-OSU/SSLClient#18]
I'm not sure if this issue is related to `SSLClient` or to `PubSubClient`.
After subscribing to an MQTT topic, I can successfully receive messages. But if the message is "too large" I get a disconnection:

For example, the message I'm expecting from AWS (`$aws/things/<thing>/shadow/get`) is about 9 kbytes large. I've plenty of RAM on my STM32 so I added:

```
#define MQTT_PACKET_SIZE  16384

SSLClientParameters mTLS = SSLClientParameters::fromPEM(certificateBuff, sizeof certificateBuff, privateKeyBuff, sizeof privateKeyBuff);
EthernetClient ethClient;
SSLClient networkClient(ethClient, TAs, (size_t)TAs_NUM, A5);
PubSubClient mqtt(mqttServer, 8883, MQTT_Callback, networkClient);

void setup()
{
    ...
    mqtt.setBufferSize(MQTT_PACKET_SIZE);
    ...
}
```

My `MQTT_Callback` doesn't require a new buffer:

```
void MQTT_Callback(char *topic, byte *payload, unsigned int length)
{
  Serial.print("Message arrived [");
  Serial.print(topic);
  Serial.print("] ");
  for (int i=0;i<length;i++) Serial.print((char)payload[i]);
  Serial.println();
}
```

This is the output:
<details>
<summary>Arduino Log</summary>
> 17:13:57.087 ->   DHCP assigned IP 192.168.1.179
> 17:13:57.087 -> [NET] MAC Address: 00:80:E1:3E:00:40
> 17:13:58.576 -> Attempting MQTT connection...connected
> 17:14:02.117 -> (SSLClient)(SSL_WARN)(m_run_until): Discarded unread data to favor a write operation
> 17:14:02.315 -> (SSLClient)(SSL_WARN)(m_run_until): Discarded unread data to favor a write operation
> 17:14:02.514 -> (SSLClient)(SSL_WARN)(m_run_until): Discarded unread data to favor a write operation
> 17:14:02.679 -> (SSLClient)(SSL_WARN)(m_run_until): Discarded unread data to favor a write operation
> 17:14:02.878 -> (SSLClient)(SSL_WARN)(m_run_until): Discarded unread data to favor a write operation
> 17:14:02.878 -> Published [$aws/things/<thing>/shadow/get] 
> 17:14:03.043 -> Attempting MQTT connection...(SSLClient)(SSL_WARN)(connect): Arduino client is already connected? Continuing anyway...
> 17:14:06.352 -> connected
> 17:14:06.518 -> (SSLClient)(SSL_WARN)(m_run_until): Discarded unread data to favor a write operation
> 17:14:06.716 -> (SSLClient)(SSL_WARN)(m_run_until): Discarded unread data to favor a write operation
> 17:14:06.882 -> (SSLClient)(SSL_WARN)(m_run_until): Discarded unread data to favor a write operation
> 17:14:07.080 -> (SSLClient)(SSL_WARN)(m_run_until): Discarded unread data to favor a write operation
> 17:14:07.246 -> (SSLClient)(SSL_WARN)(m_run_until): Discarded unread data to favor a write operation
> 17:14:07.279 -> Published [$aws/things/<thing>/shadow/get] 
> 17:14:07.411 -> Attempting MQTT connection...(SSLClient)(SSL_WARN)(connect): Arduino client is already connected? Continuing anyway...
> 17:14:10.753 -> connected
> 17:14:10.919 -> (SSLClient)(SSL_WARN)(m_run_until): Discarded unread data to favor a write operation
> 17:14:11.084 -> (SSLClient)(SSL_WARN)(m_run_until): Discarded unread data to favor a write operation
> ...
> 
</details>

I also tried to enable logging, and this is the new output:

<details>
<summary>Arduino Log</summary>
>   DHCP assigned IP 192.168.1.179
> 17:18:45.719 -> [NET] MAC Address: 00:80:E1:3E:00:40
> 17:18:47.208 -> Attempting MQTT connection...(SSLClient)(SSL_INFO)(connect): Base client connected!
> 17:18:47.406 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:47.406 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:47.406 ->    RECVREC
> 17:18:47.406 -> (SSLClient)(SSL_INFO)(m_run_until): Expected bytes count: 
> 17:18:47.439 -> (SSLClient)(SSL_INFO)(m_run_until): 5
> 17:18:50.384 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:50.417 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:50.417 ->    RECVREC
> 17:18:50.417 ->    SENDAPP
> 17:18:50.417 -> (SSLClient)(SSL_INFO)(m_start_ssl): Connection successful!
> 17:18:50.583 -> connected
> 17:18:50.583 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:50.583 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:50.616 ->    SENDAPP
> 17:18:50.616 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:50.616 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:50.616 ->    RECVREC
> 17:18:50.616 ->    SENDAPP
> 17:18:50.616 -> (SSLClient)(SSL_INFO)(m_run_until): Expected bytes count: 
> 17:18:50.616 -> (SSLClient)(SSL_INFO)(m_run_until): 5
> 17:18:50.781 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:50.781 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:50.781 ->    RECVAPP
> 17:18:50.781 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:50.781 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:50.781 ->    RECVAPP
> 17:18:50.781 -> (SSLClient)(SSL_WARN)(m_run_until): Discarded unread data to favor a write operation
> 17:18:50.815 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:50.815 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:50.815 ->    RECVREC
> 17:18:50.815 ->    SENDAPP
> 17:18:50.815 -> (SSLClient)(SSL_INFO)(m_run_until): Expected bytes count: 
> 17:18:50.815 -> (SSLClient)(SSL_INFO)(m_run_until): 5
> 17:18:50.815 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:50.848 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:50.848 ->    SENDAPP
> 17:18:50.848 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:50.848 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:50.848 ->    RECVREC
> 17:18:50.848 ->    SENDAPP
> 17:18:50.848 -> (SSLClient)(SSL_INFO)(m_run_until): Expected bytes count: 
> 17:18:50.848 -> (SSLClient)(SSL_INFO)(m_run_until): 5
> 17:18:50.980 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:51.013 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:51.013 ->    RECVAPP
> 17:18:51.013 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:51.013 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:51.013 ->    RECVAPP
> 17:18:51.013 -> (SSLClient)(SSL_WARN)(m_run_until): Discarded unread data to favor a write operation
> 17:18:51.046 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:51.046 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:51.046 ->    RECVREC
> 17:18:51.046 ->    SENDAPP
> 17:18:51.046 -> (SSLClient)(SSL_INFO)(m_run_until): Expected bytes count: 
> 17:18:51.046 -> (SSLClient)(SSL_INFO)(m_run_until): 5
> 17:18:51.046 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:51.046 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:51.046 ->    SENDAPP
> 17:18:51.152 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:51.152 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:51.152 ->    RECVREC
> 17:18:51.152 ->    SENDAPP
> 17:18:51.152 -> (SSLClient)(SSL_INFO)(m_run_until): Expected bytes count: 
> 17:18:51.152 -> (SSLClient)(SSL_INFO)(m_run_until): 5
> 17:18:51.311 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:51.311 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:51.311 ->    RECVAPP
> 17:18:51.311 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:51.311 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:51.344 ->    RECVAPP
> 17:18:51.344 -> (SSLClient)(SSL_WARN)(m_run_until): Discarded unread data to favor a write operation
> 17:18:51.344 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:51.344 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:51.344 ->    RECVREC
> 17:18:51.344 ->    SENDAPP
> 17:18:51.344 -> (SSLClient)(SSL_INFO)(m_run_until): Expected bytes count: 
> 17:18:51.377 -> (SSLClient)(SSL_INFO)(m_run_until): 5
> 17:18:51.377 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:51.377 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:51.377 ->    SENDAPP
> 17:18:51.377 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:51.377 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:51.377 ->    RECVREC
> 17:18:51.377 ->    SENDAPP
> 17:18:51.377 -> (SSLClient)(SSL_INFO)(m_run_until): Expected bytes count: 
> 17:18:51.410 -> (SSLClient)(SSL_INFO)(m_run_until): 5
> 17:18:51.542 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:51.542 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:51.542 ->    RECVAPP
> 17:18:51.542 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:51.542 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:51.542 ->    RECVAPP
> 17:18:51.542 -> (SSLClient)(SSL_WARN)(m_run_until): Discarded unread data to favor a write operation
> 17:18:51.575 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:51.575 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:51.575 ->    RECVREC
> 17:18:51.575 ->    SENDAPP
> 17:18:51.575 -> (SSLClient)(SSL_INFO)(m_run_until): Expected bytes count: 
> 17:18:51.575 -> (SSLClient)(SSL_INFO)(m_run_until): 5
> 17:18:51.575 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:51.609 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:51.609 ->    SENDAPP
> 17:18:51.609 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:51.609 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:51.609 ->    RECVREC
> 17:18:51.609 ->    SENDAPP
> 17:18:51.609 -> (SSLClient)(SSL_INFO)(m_run_until): Expected bytes count: 
> 17:18:51.609 -> (SSLClient)(SSL_INFO)(m_run_until): 5
> 17:18:51.774 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:51.774 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:51.774 ->    RECVAPP
> 17:18:51.774 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:51.774 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:51.774 ->    RECVAPP
> 17:18:51.774 -> (SSLClient)(SSL_WARN)(m_run_until): Discarded unread data to favor a write operation
> 17:18:51.807 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:51.807 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:51.807 ->    RECVREC
> 17:18:51.807 ->    SENDAPP
> 17:18:51.807 -> (SSLClient)(SSL_INFO)(m_run_until): Expected bytes count: 
> 17:18:52.800 -> (SSLClient)(SSL_INFO)(m_run_until): 5
> 17:18:52.965 -> (SSLClient)(SSL_INFO)(available): Engine closed after update
> 17:18:52.965 -> Attempting MQTT connection...(SSLClient)(SSL_WARN)(connect): Arduino client is already connected? Continuing anyway...
> 17:18:53.098 -> (SSLClient)(SSL_INFO)(connect): Base client connected!
> 17:18:53.098 -> (SSLClient)(SSL_INFO)(m_get_session_index): <account>.iot.us-east-2.amazonaws.com
> 17:18:53.131 -> (SSLClient)(SSL_INFO)(getSession): Using session index: 
> 17:18:53.131 -> (SSLClient)(SSL_INFO)(getSession): 0
> 17:18:53.131 -> (SSLClient)(SSL_INFO)(m_start_ssl): Set SSL session!
> 17:18:53.131 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:53.131 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:53.164 ->    RECVREC
> 17:18:53.164 -> (SSLClient)(SSL_INFO)(m_run_until): Expected bytes count: 
> 17:18:53.164 -> (SSLClient)(SSL_INFO)(m_run_until): 5
> 17:18:56.109 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:56.109 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:56.142 ->    RECVREC
> 17:18:56.142 ->    SENDAPP
> 17:18:56.142 -> (SSLClient)(SSL_INFO)(m_start_ssl): Connection successful!
> 17:18:56.308 -> connected
> 17:18:56.308 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:56.308 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:56.308 ->    SENDAPP
> 17:18:56.308 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:56.308 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:56.341 ->    RECVREC
> 17:18:56.341 ->    SENDAPP
> 17:18:56.341 -> (SSLClient)(SSL_INFO)(m_run_until): Expected bytes count: 
> 17:18:56.341 -> (SSLClient)(SSL_INFO)(m_run_until): 5
> 17:18:56.473 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:56.473 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:56.473 ->    RECVAPP
> 17:18:56.473 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:56.473 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:56.506 ->    RECVAPP
> 17:18:56.506 -> (SSLClient)(SSL_WARN)(m_run_until): Discarded unread data to favor a write operation
> 17:18:56.506 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:56.506 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:56.506 ->    RECVREC
> 17:18:56.506 ->    SENDAPP
> 17:18:56.506 -> (SSLClient)(SSL_INFO)(m_run_until): Expected bytes count: 
> 17:18:56.539 -> (SSLClient)(SSL_INFO)(m_run_until): 5
> 17:18:56.539 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:56.539 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:56.539 ->    SENDAPP
> 17:18:56.539 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:56.539 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:56.539 ->    RECVREC
> 17:18:56.539 ->    SENDAPP
> 17:18:56.539 -> (SSLClient)(SSL_INFO)(m_run_until): Expected bytes count: 
> 17:18:56.572 -> (SSLClient)(SSL_INFO)(m_run_until): 5
> 17:18:56.705 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:56.705 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:56.705 ->    RECVAPP
> 17:18:56.705 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:56.705 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:56.738 ->    RECVAPP
> 17:18:56.738 -> (SSLClient)(SSL_WARN)(m_run_until): Discarded unread data to favor a write operation
> 17:18:56.738 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:56.738 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:56.738 ->    RECVREC
> 17:18:56.738 ->    SENDAPP
> 17:18:56.738 -> (SSLClient)(SSL_INFO)(m_run_until): Expected bytes count: 
> 17:18:56.771 -> (SSLClient)(SSL_INFO)(m_run_until): 5
> 17:18:56.771 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:56.771 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:56.771 ->    SENDAPP
> 17:18:56.771 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:56.771 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:56.771 ->    RECVREC
> 17:18:56.771 ->    SENDAPP
> 17:18:56.804 -> (SSLClient)(SSL_INFO)(m_run_until): Expected bytes count: 
> 17:18:56.804 -> (SSLClient)(SSL_INFO)(m_run_until): 5
> 17:18:56.936 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:56.936 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:56.936 ->    RECVAPP
> 17:18:56.936 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:56.969 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:56.969 ->    RECVAPP
> 17:18:56.969 -> (SSLClient)(SSL_WARN)(m_run_until): Discarded unread data to favor a write operation
> 17:18:56.969 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:56.969 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:56.969 ->    RECVREC
> 17:18:56.969 ->    SENDAPP
> 17:18:57.002 -> (SSLClient)(SSL_INFO)(m_run_until): Expected bytes count: 
> 17:18:57.002 -> (SSLClient)(SSL_INFO)(m_run_until): 5
> 17:18:57.002 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:57.002 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:57.002 ->    SENDAPP
> 17:18:57.002 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:57.002 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:57.036 ->    RECVREC
> 17:18:57.036 ->    SENDAPP
> 17:18:57.036 -> (SSLClient)(SSL_INFO)(m_run_until): Expected bytes count: 
> 17:18:57.036 -> (SSLClient)(SSL_INFO)(m_run_until): 5
> 17:18:57.168 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:57.168 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:57.201 ->    RECVAPP
> 17:18:57.201 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:57.201 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:57.201 ->    RECVAPP
> 17:18:57.201 -> (SSLClient)(SSL_WARN)(m_run_until): Discarded unread data to favor a write operation
> 17:18:57.201 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:57.201 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:57.234 ->    RECVREC
> 17:18:57.234 ->    SENDAPP
> 17:18:57.234 -> (SSLClient)(SSL_INFO)(m_run_until): Expected bytes count: 
> 17:18:57.234 -> (SSLClient)(SSL_INFO)(m_run_until): 5
> 17:18:57.234 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:57.234 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:57.234 ->    SENDAPP
> 17:18:57.234 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:57.234 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:57.267 ->    RECVREC
> 17:18:57.267 ->    SENDAPP
> 17:18:57.267 -> (SSLClient)(SSL_INFO)(m_run_until): Expected bytes count: 
> 17:18:57.267 -> (SSLClient)(SSL_INFO)(m_run_until): 5
> 17:18:57.400 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:57.400 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:57.400 ->    RECVAPP
> 17:18:57.400 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:57.433 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:57.433 ->    RECVAPP
> 17:18:57.433 -> (SSLClient)(SSL_WARN)(m_run_until): Discarded unread data to favor a write operation
> 17:18:57.433 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 17:18:57.433 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 17:18:57.433 ->    RECVREC
> 17:18:57.433 ->    SENDAPP
> 17:18:57.433 -> (SSLClient)(SSL_INFO)(m_run_until): Expected bytes count: 
> 17:18:58.458 -> (SSLClient)(SSL_INFO)(m_run_until): 5
> ...
> 
</details>

**Comment by Mark-81** [comment]
Hacking the library and setting:

    unsigned char m_iobuf[BR_SSL_BUFSIZE_BIDI];

leads to fix the disconnection as well as the warning "Discarded unread data to favor a write operation", but the published message is still not received.

**Comment by prototypicalpro** [comment]
Could you post the logs with your modified version of the library?

**Comment by Mark-81** [comment]
Here the full log:

> 09:19:35.474 -> [NET] DHCP assigned IP: 192.168.1.179
> 09:19:35.474 -> [NET] MAC Address: 00:80:E1:3E:00:40
> 09:19:35.474 -> [MQTT] Connecting...(SSLClient)(SSL_INFO)(connect): Base client connected!
> 09:19:35.706 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 09:19:35.706 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 09:19:35.739 ->    RECVREC
> 09:19:35.739 -> (SSLClient)(SSL_INFO)(m_run_until): Expected bytes count: 
> 09:19:35.739 -> (SSLClient)(SSL_INFO)(m_run_until): 5
> 09:19:38.717 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 09:19:38.717 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 09:19:38.717 ->    RECVREC
> 09:19:38.717 ->    SENDAPP
> 09:19:38.717 -> (SSLClient)(SSL_INFO)(m_start_ssl): Connection successful!
> 09:19:38.949 -> connected
> 09:19:38.982 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 09:19:38.982 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 09:19:38.982 ->    RECVREC
> 09:19:38.982 ->    SENDAPP
> 09:19:38.982 -> (SSLClient)(SSL_INFO)(m_run_until): Expected bytes count: 
> 09:19:38.982 -> (SSLClient)(SSL_INFO)(m_run_until): 5
> 09:19:39.148 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 09:19:39.148 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 09:19:39.148 ->    SENDAPP
> 09:19:39.148 ->    RECVAPP
> 09:19:39.148 -> [MQTT] Subscribed to: $aws/things/thing/shadow/update/#
> 09:19:39.181 -> (SSLClient)(SSL_INFO)(m_run_until): m_run changed state:
> 09:19:39.181 -> (SSLClient)(SSL_INFO)(m_run_until): State: 
> 09:19:39.181 ->    SENDAPP
> 09:19:39.181 ->    RECVAPP
> 09:19:39.181 -> [MQTT] Subscribed to: $aws/things/thing/shadow/get/#
> 09:19:39.181 -> [MQTT] Publish $aws/things/thing/shadow/get: 
> 09:19:39.181 -> [MQTT] Publish return code: 1

To be sure, on my development machine I subscribed to the same topics using `mosquitto_sub` (of course using a different client id) and after publishing the null message on `shadow/get` I receive the answer message there.

Please feel free to ask anything else I can do to help you to understand what's going on.

**Comment by prototypicalpro** [comment]
It looks like this is an issue with PubSubClient not being able to handle a buffer size larger than 256 bytes: https://github.com/knolleary/pubsubclient/issues/764. If there were some way you could test your server without SSLClient we could confirm this. I'm going to assume that PubSubClient is the issue for now because the logs you posted look correct.

Unfortunately this doesn't leave us with a lot of good solutions to the problem. Glancing at the PubSubClient source, I noticed this code is assigning a `uint16_t` to a `uint8_t*` type: https://github.com/knolleary/pubsubclient/blob/2d228f2f862a95846c65a8518c79f48dfc8f188c/src/PubSubClient.cpp#L334. It's possible that this is causing an integer overflow and as a result the payload is being incorrectly read--if you are feeling particularly determined, you could attempt to fix that bug yourself and see if it improves the issue. Another possible option is changing the MQTT client you are using to a different one such as https://bitbucket.org/amotzek/mqtt-client/src/master/ or https://github.com/256dpi/arduino-mqtt.

Let me know what you end up doing, I'd love to incorporate your fix into the examples if you figure it out.

**Comment by Mark-81** [comment]
Unfortunately I had not enough time to debug it... so I ended up to "trim" the published messages so they fit into a couple of kbytes and now all works fine. After the completion of the project I'm going to try again with larger messages.

**Comment by prototypicalpro** [comment]
I'm going to go ahead and close this issue since it seems like an issue with PubSubClient (or at least an older version of it), feel free to re-open it if you find any indicators that the issue is with SSLClient.
