### ISSUE TITLE
support for TLS PSK

### ISSUE THREAD

**Issue by pat1** [OPEnSLab-OSU/SSLClient#31]
I have to implement a client for MQTTS with mosquitto as broker with TLS PSK.
I cannot understand if this library support TLS PSK (Pre-Shared Key) and how implement it .

Many thanks in advance for any suggestion

Paolo

**Comment by prototypicalpro** [comment]
Are you referring to something like this: https://cdpstudio.com/manual/cdp/mqttio/mqttio-psk-setup.html? Unfortunately I don't think BearSSL supports any authentication method other than client certificates, which means that SSLClient doesn't support them either. Your best bet is probably [MbedTLS](https://github.com/ARMmbed/mbedtls), which _should_ support TLS PSK.
