### ISSUE TITLE
What a treasure I have discovered here, is speak-less. 

### ISSUE THREAD

**Issue by woodlist** [OPEnSLab-OSU/SSLClient#40]
**Describe the bug**
I did not find appropriate label to mark this post. May God bless the creator of this library.
Wow, wow wow!!!!!! I'm happy for accidental discover of this repository.

**To Reproduce**
Write some steps to reproduce the behavior. Be sure to include the vant hardware required, if any.

**Expected behavior**
It is already just FINE!

**Screenshots/Serial Output**
If applicable, add screenshots or serial logs to help explain your problem.

**Context (please complete the following information):**
 -  ESP32
 - Arduino Core Version 1.8.13

**Additional context**

**Comment by prototypicalpro** [comment]
Thanks! I appreciate the feedback😁.
