### ISSUE TITLE
Error writing to m_client on ESP32

### ISSUE THREAD

**Issue by bkaraceylan** [OPEnSLab-OSU/SSLClient#44]
**Describe the bug**
ESP32dev board with ec28j60 ethernet module.
Using UIPEthernet library.
EthernetHTTPS example works fine however my program returns this error.
Free heap memory before connection request is 226416.

**To Reproduce**
Send a request to an SSL endpoint using the hardware setup mentioned above.

**Expected behavior**
Return html content.

**Screenshots/Serial Output**
(SSLClient)(SSL_ERROR)(m_update_engine): Error writing to m_client
(SSLClient)(SSL_ERROR)(m_update_engine): 0
(SSLClient)(SSL_ERROR)(connected): Not connected because write error is set
(SSLClient)(SSL_ERROR)(m_print_ssl_error): SSL_CLIENT_WRITE_FAIL
(SSLClient)(SSL_WARN)(m_run_until): Terminating with write error: 
(SSLClient)(SSL_WARN)(m_run_until): 4
(SSLClient)(SSL_ERROR)(m_start_ssl): Failed to initlalize the SSL layer
(SSLClient)(SSL_ERROR)(m_print_br_error): Unknown error code: 0

**Context (please complete the following information):**
platform = espressif32
board = esp32dev
framework = arduino
uipethernet/UIPEthernet@^2.0.9
openslab-osu/SSLClient@^1.6.11
build_flags = 	-D BEARSSL_SSL_BASIC

**Comment by bkaraceylan** [comment]
UIPEthernet seems to be the underlying cause. Closing this.

**Comment by woodlist** [comment]
This exact case happens with my connections very frequently too.

**Comment by rohitsam** [comment]
Happens for me on esp32 wifi, any fix to this?

**Comment by faizurrehman** [comment]
Is it fixed? I am facing similar issue with esp32

**Comment by nada0302** [comment]
I have an same issue with esp32 using example AWSIoT...

**Comment by MeY0u** [comment]
still no fix?
